apiVersion: v1 # a versão do Kubernetes necessária para criar objetos do tipo PersistentVolumeClaim
kind: PersistentVolumeClaim # o tipo do objeto a ser criado
metadata:  # informações que ajudam a identificar de forma única o objeto (por exemplo: name, UID)
  name: mysql-pv-claim
  namespace: labwordpress
  labels:
    app: wordpress
spec: # estado do PersistentVolumeClaim a ser criado
  accessModes:
    - ReadWriteOnce # o volume pode ser montado como leitura-escrita por um nó único
  resources:
    requests: # mínimo de recursos computacional requerido
      storage: 3G